
name = "venture"

compatibility_date = "2026-05-03"
main = "index.js"

[env]
name = "venture"
type = "javascript"

[vars]
# No secrets stored here; use `wrangler secret put ""` to set the secret

[[kv_namespaces]]
binding = "RATE_KV"
id = "REPLACE_WITH_KV_ID" # set your KV namespace id here before publishing (replace after creating KV)
