
name = "venture"

compatibility_date = "2026-05-03"
main = "index.js"

[env]
name = "venture"
type = "javascript"

[vars]
# No secrets stored here; use `wrangler secret put TURNSTILE_SECRET` to set the secret
